"""Known spellings, so the review screen can flag a likely typo.

**Ours, not the client's** -- a placeholder list written for the review screen
on 2026-09-23, and `VOCABULARY_VERSION` says so; a test holds the prefix.

It only ever decides whether to *ask* the candidate about an item. A skill
missing from this list is never flagged, is never dropped, and nothing here
reaches scoring: the model reads the text the candidate confirms, not this.
"""

from __future__ import annotations

from typing import Final

VOCABULARY_VERSION: Final = "placeholder-2026-09-23"

SKILLS: Final[tuple[str, ...]] = (
    # Office and general
    "MS Office",
    "Microsoft Office",
    "MS Excel",
    "Microsoft Excel",
    "Excel",
    "MS Word",
    "Microsoft Word",
    "PowerPoint",
    "MS PowerPoint",
    "Google Sheets",
    "Google Docs",
    "Outlook",
    "Tally",
    "Tally ERP",
    "SAP",
    "Data Entry",
    "Typing",
    "Documentation",
    "Report Writing",
    "Lab Reporting",
    # Soft skills
    "Teamwork",
    "Team Work",
    "Leadership",
    "Communication",
    "Communication Skills",
    "Problem Solving",
    "Time Management",
    "Critical Thinking",
    "Customer Service",
    "Negotiation",
    "Presentation",
    "Public Speaking",
    "Adaptability",
    "Collaboration",
    "Decision Making",
    # Software
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Kotlin",
    "Swift",
    "Golang",
    "Rust",
    "Ruby",
    "PHP",
    "Scala",
    "MATLAB",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue",
    "Node.js",
    "Express",
    "Django",
    "Flask",
    "FastAPI",
    "Spring",
    "Spring Boot",
    "Flutter",
    "Android",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Oracle",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Linux",
    "Git",
    "GitHub",
    "Jenkins",
    "AWS",
    "Azure",
    "Google Cloud",
    "Machine Learning",
    "Deep Learning",
    "Data Analysis",
    "Data Science",
    "Statistics",
    "Pandas",
    "NumPy",
    "TensorFlow",
    "PyTorch",
    "Power BI",
    "Tableau",
    "AutoCAD",
    "SolidWorks",
    "Photoshop",
    "Illustrator",
    "Figma",
    "Canva",
    # Business and finance operations
    "Accounting",
    "Bookkeeping",
    "Taxation",
    "GST",
    "Auditing",
    "Payroll",
    "Sales",
    "Marketing",
    "Digital Marketing",
    "SEO",
    "Social Media Marketing",
    "Content Writing",
    "Copywriting",
    "Recruitment",
    "Project Management",
    "Operations",
    "Inventory Management",
    "Supply Chain",
    "Logistics",
    # Laboratory and health
    "Microbiology",
    "Microbial Culturing",
    "PCR",
    "Spectrophotometry",
    "Chromatography",
    "Titration",
    "Pipetting",
    "Cell Culture",
    "Quality Control",
    "Quality Assurance",
    "Nursing",
    "Pharmacology",
)

LANGUAGES: Final[tuple[str, ...]] = (
    "English",
    "Hindi",
    "Bengali",
    "Marathi",
    "Telugu",
    "Tamil",
    "Gujarati",
    "Urdu",
    "Kannada",
    "Odia",
    "Malayalam",
    "Punjabi",
    "Assamese",
    "Maithili",
    "Sanskrit",
    "Konkani",
    "Nepali",
    "Sindhi",
    "Kashmiri",
    "Dogri",
    "Manipuri",
    "Santali",
    "French",
    "German",
    "Spanish",
    "Japanese",
    "Mandarin",
    "Arabic",
)
